server.port=8080

auth.service.url=http://localhost:8081
expense.service.url=http://localhost:8082
income.service.url=http://localhost:8083
category.service.url=http://localhost:8084
budget.service.url=http://localhost:8085
analytics.service.url=http://localhost:8086
recurring.service.url=http://localhost:8087
notification.service.url=http://localhost:8088